[workspace]

members = [
  "starlane",
  "starlane-core",
  "mesh-portal",
  "mesh-portal-versions",
  "cosmic-nom",
  "cosmic-macros",
  "cosmic-macros-primitive",
  "cosmic-portal-cli",
  "cosmic-lanes",
  "cosmic-lanes-quic",
  "cosmic-locality",
  "cosmic-core"
  ]
